version: "3.9"
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml"
      - "./grafana/dashboards/:/var/lib/grafana/dashboards/"
      - "./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml"
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - "./grafana/prometheus.yml:/prometheus/prometheus.yml"
    command:
      - "--web.enable-admin-api"
  choshsh-ui:
    image: choshsh/choshsh-ui:latest
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"