{
 "title": "Kubernetes All-in-one Cluster Monitoring KR",
 "description": "This dashboard is one of major topic for Kubernetes Book \nand best optimized for virtual machine environment provided with \nhttps://github.com/sysnet4admin/_Book_k8sInfra\n\nNotice: It may be running on the other environment but cannot be guaranteed.",
 "tags": [
  "kubernetes",
  "k8s",
  "Metric"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(node_uname_info,kubernetes_node)"
    }
   },
   { "name": "duration", "query": "1m,5m,10m,30m,1h" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_uname_info{kubernetes_node=\"$node\"}, instance)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_labels, namespace)"
    }
   },
   {
    "name": "deployment",
    "query": {
     "query": "label_values(kube_deployment_spec_replicas{namespace=\"$namespace\"}, deployment)"
    }
   },
   {
    "name": "statefulset",
    "query": {
     "query": "label_values(kube_statefulset_replicas{namespace=\"$namespace\"}, statefulset)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\"},  pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "클러스터 요약", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Control Plane 정상 가동률",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\navg_over_time((sum without ()(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.calico.*|.*.flannel.*|.*.etcd.*\"}) \n/ \ncount without ()(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.calico.*|.*.flannel.*|.*.etcd.*\"}))[$duration:5m])\n)"
    }
   ]
  },
  {
   "title": "노드 현황",
   "type": "table",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "targets": [
    { "expr": "kube_node_info", "legendFormat": "{{node}}" },
    {
     "expr": " (count by (node)(container_spec_memory_reservation_limit_bytes{pod!=\"\"}))"
    },
    {
     "expr": "max\n  by(node) (max by(instance) (kubelet_running_pod_count{job=\"kubelet\",metrics_path=\"/metrics\"})\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\"})\n"
    },
    {
     "expr": "sum by (node)(label_replace(instance:node_cpu:ratio + on(instance) group_left(nodename) \nnode_uname_info,\"node\",\"$1\",\"nodename\", \"(.+)\") ) / sum by (node)(kube_node_status_capacity{resource=\"cpu\"})"
    },
    { "expr": "kube_node_role" },
    {
     "expr": "label_replace(up{job=\"kubernetes-nodes\"}, \"node\", \"$1\", \"instance\", \"(.+)\")"
    },
    {
     "expr": "label_replace(avg by (kubernetes_node) (time() - node_boot_time_seconds), \"node\", \"$1\", \"kubernetes_node\", \"(.+)\")"
    }
   ]
  },
  {
   "title": "네임스페이스",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(kube_namespace_created)", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "정상 Pod",
   "type": "stat",
   "description": "Running",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "비정상 Pod",
   "type": "stat",
   "description": "Failed | Pending | Unknown",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=~\"Failed|Pending|Unknown\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "전체 클러스터", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "노드별 CPU 점유율",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg by (instance,kubernetes_node) (rate(node_cpu_seconds_total{mode=\"idle\"}[$duration]))",
     "legendFormat": "{{kubernetes_node}} "
    }
   ]
  },
  {
   "title": "노드별 메모리 사용량",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)\n/\nnode_memory_MemTotal_bytes\n*\n100",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "초당 네트워크 트래픽",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes", "label": "수신 | 송신" }
   ],
   "targets": [
    {
     "expr": "sum (rate(node_network_receive_bytes_total[$duration]))",
     "legendFormat": "{{kubernetes_node}}(in)"
    },
    {
     "expr": "sum (rate(node_network_transmit_bytes_total[$duration]))",
     "legendFormat": "{{kubernetes_node}}(out)"
    }
   ]
  },
  {
   "title": "API 서버 호출",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (verb) (rate(apiserver_request_total[$duration]))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  { "title": "노드 [$node]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU 점유율",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!~\"guest.*|idle|iowait\", kubernetes_node=\"$node\"}[5m]))"
    }
   ]
  },
  {
   "title": "메모리 점유율",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{kubernetes_node=\"$node\"}-node_memory_MemAvailable_bytes{kubernetes_node=\"$node\"})/node_memory_MemTotal_bytes{kubernetes_node=\"$node\"}"
    }
   ]
  },
  {
   "title": "디스크 사용률(%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{kubernetes_node=\"$node\"} - node_filesystem_avail_bytes{kubernetes_node=\"$node\"}) by (kubernetes_node) / sum(node_filesystem_size_bytes{kubernetes_node=\"$node\"}) by (kubernetes_node)"
    }
   ]
  },
  {
   "title": "CPU 코어",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_node_status_allocatable_cpu_cores{node=\"$node\"}"
    }
   ]
  },
  {
   "title": "File descriptor / Context switches",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "used filefd" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$instance\"}",
     "legendFormat": "used filefd"
    },
    {
     "expr": "rate(node_context_switches_total{instance=~\"$instance\"}[$duration])",
     "legendFormat": "switches"
    }
   ]
  },
  {
   "title": "Disk IOPS 완료",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 17 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=~\"$instance\"}[$duration])",
     "legendFormat": "{{device}}_Reads"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{instance=~\"$instance\"}[$duration])",
     "legendFormat": "{{device}}_Writes"
    },
    {
     "expr": "node_disk_io_now{instance=~\"$instance\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "메모리",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "machine_memory_bytes{instance=\"$node\"}"
    }
   ]
  },
  { "title": "Deployment [$deployment]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Deployment 생성시간",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(time()-kube_deployment_created{deployment=\"$deployment\"})",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Desired",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_deployment_spec_replicas{deployment=\"$deployment\"})",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Replicas 상태",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 24 },
   "targets": [
    {
     "expr": "avg(kube_deployment_status_replicas_available{deployment=\"$deployment\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Probe 실패",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(prober_probe_total{result=\"failed\",pod=~\"$deployment.+\"}[1m])) by (pod, probe_type)",
     "legendFormat": "{{pod}} ({{probe_type}})"
    }
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_deployment_status_replicas_available{deployment=\"$deployment\"})",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Unvailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_deployment_status_replicas_unavailable{deployment=\"$deployment\"})",
     "legendFormat": "Value"
    }
   ]
  },
  { "title": "Statefulset [$statefulset]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Statefulset 생성시간",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(time()-kube_statefulset_created{statefulset=\"$statefulset\"})",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Desired",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_statefulset_replicas{statefulset=\"$statefulset\"})",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Replicas 상태",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 31 },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{statefulset=\"$statefulset\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Probe 실패",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 31 },
   "targets": [
    {
     "expr": "sum(increase(prober_probe_total{result=\"failed\", pod=~\"loki-0\"}[1m])) by (pod, probe_type) ",
     "legendFormat": "{{pod}} ({{probe_type}})"
    }
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_replicas{statefulset=\"$statefulset\"}",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Unvailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_replicas{statefulset=\"$statefulset\"} - kube_statefulset_status_replicas_ready{statefulset=\"$statefulset\"}",
     "legendFormat": "Value"
    }
   ]
  },
  { "title": "Pod [$pod]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Pod 생성시간",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time()-kube_pod_start_time{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Owner Kind",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_owner{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "CPU 사용량",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{pod=~\"$pod\",container!=\"\"}[$duration])) by (pod) * 100",
     "legendFormat": "Use"
    }
   ]
  },
  {
   "title": "메모리 사용량",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"$pod\",container!=\"\"}) by (container)",
     "legendFormat": "{{container}} (Use)"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"$pod\",container!=\"\"}) by (container)",
     "legendFormat": "{{container}} (Limit)"
    }
   ]
  },
  {
   "title": "Pod 가동 상태",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting_reason{pod=\"$pod\", reason!~\"ContainerCreating\"})"
    }
   ]
  },
  {
   "title": "초당 네트워크 트래픽",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 44 },
   "yaxes": [
    { "format": "decbytes", "label": "수신 | 송신" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=\"$pod\"}[$duration]))",
     "legendFormat": "in"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=\"$pod\"}[$duration]))",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Probe 실패",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 44 },
   "targets": [
    {
     "expr": "increase(prober_probe_total{result=\"failed\", pod=\"$pod\"}[1m])",
     "legendFormat": "{{container}} ({{probe_type}})"
    }
   ]
  }
 ]
}