{
 "title": "Kube Control Plane Log",
 "description": "컨트롤 플레인 로그 모니터링 (kube-api-server, kube-controller-manager, etcd ..)",
 "tags": [
  "logging",
  "Loki",
  "k8s",
  "control_plane "
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "searchable_pattern", "label": "Search (case insensitive)" },
   {
    "name": "domain",
    "query": "http://loki-grafana.choshsh.com/d/JqglEFN7z/kubernetes-components"
   }
  ]
 },
 "panels": [
  {
   "title": "전체 (Click value)",
   "type": "stat",
   "description": "쿠버네티스 컴포넌트 총 로그 개수",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({tier=\"control-plane\"} )[$__interval]))"
    }
   ]
  },
  {
   "title": "Error (Click value)",
   "type": "stat",
   "description": "컴포넌트 error 로그 개수",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({tier=\"control-plane\"} |~ \"(?i)error\" )[$__interval])) "
    }
   ]
  },
  {
   "title": "Warn (Click value)",
   "type": "stat",
   "description": "컴포넌트 wanr 로그 개수",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({tier=\"control-plane\"} |~ \"(?i)warn\" )[$__interval])) "
    }
   ]
  },
  {
   "title": "검색 : [ $searchable_pattern ]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({tier=\"control-plane\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "kube-controller-manager",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{tier=\"control-plane\", component=\"kube-controller-manager\"} |~ \"(?i)$searchable_pattern\" \n| pattern `<ts> <stream> <_> <_> <_> 1 <caller>] <msg>` \n| line_format \" [{{.caller}}] {{.msg}}\""
    }
   ]
  },
  {
   "title": "kube-apiserver",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "{tier=\"control-plane\", component=\"kube-apiserver\"}  != \"Trace[\" != \"Header: map[Content-Type:[text/plain; charset=utf-8] X-Content-Type-Options:[nosniff]]\"\n|~ \"(?i)$searchable_pattern\" \n| pattern `<ts> <stream> <_> <_> <_> 1 <caller>] <msg>` \n| line_format \"[{{.caller}}] {{.msg}}\""
    }
   ]
  },
  {
   "title": "kube-scheduler",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{tier=\"control-plane\", component=\"kube-scheduler\"} |~ \"(?i)$searchable_pattern\" \n| pattern \"<ts> <stream> <_> <_> <_> 1 <caller>] <msg>\"\n| line_format \"[{{.caller}}] {{.msg}}\""
    }
   ]
  },
  {
   "title": "etcd",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "{namespace=\"kube-system\", component=\"etcd\"} |~ \"(?i)$searchable_pattern\" \n| pattern `<ts> <stream> <_> <msg>` | line_format `{{.msg}}` | json | __error__ = \"\" \n| line_format \"{{.level}} [{{.caller}}] {{.msg}}\""
    }
   ]
  },
  {
   "title": "CoreDNS",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{namespace=\"kube-system\", k8s_app=\"kube-dns\"} |~ \"(?i)$searchable_pattern\" \n| pattern `<ts> <stream> <_> [<level>] <msg>` \n| line_format \"{{.level}}\\t{{.msg}}\""
    }
   ]
  },
  {
   "title": "Kube-Proxy",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "{k8s_app=\"kube-proxy\"} |~ \"(?i)$searchable_pattern\" \n| pattern `<ts> <stream> <_> <_> <_> 1 <caller>] <msg>` \n| line_format \"[{{.caller}}] {{.msg}}\""
    }
   ]
  }
 ]
}