{
 "title": "Kube All-resource Log",
 "description": "쿠버네티스 로그 모니터링",
 "tags": [
  "Loki",
  "logging",
  "k8s"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values({namespace!=\"monitoring\"},namespace)"
    }
   },
   {
    "name": "pod_name",
    "label": "Pod",
    "query": "label_values({namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "container_name",
    "label": "Container",
    "query": "label_values({namespace=~\"$namespace\", pod=~\"$pod_name\"}, container)"
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)", "query": "error" }
  ]
 },
 "panels": [
  {
   "title": "전체 (Click to search)",
   "type": "stat",
   "description": "전체 로그",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n    (\n      {namespace=~\"$namespace\", namespace!~\"monitoring\", container=~\"$container_name\", pod=~\"$pod_name\"}\n        != \"var-searchable_pattern\"\n        != \"caller=metrics.go\"\n        !~ \"(?i)no_error\"\n    )[$__interval]\n  )\n)"
    }
   ]
  },
  {
   "title": "Error (Click to search)",
   "type": "stat",
   "description": "에러 로그",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n    (\n      {namespace=~\"$namespace\", namespace!~\"monitoring\", container=~\"$container_name\", pod=~\"$pod_name\"}\n        |~ \"(?i)error\"\n        != \"caller=metrics.go\"\n        !~ \"(?i)no_error\"\n        != \"var-searchable_pattern\"\n    )[$__interval]\n  )\n)"
    }
   ]
  },
  {
   "title": "Warn (Click value)",
   "type": "stat",
   "description": "경로 로그",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n    (\n      {namespace=~\"$namespace\", namespace!~\"monitoring\", container=~\"$container_name\", pod=~\"$pod_name\"}\n        |~ \"(?i)warn\" \n        != \"caller=metrics.go\"\n        !~ \"(?i)no_error\"\n        != \"var-searchable_pattern\"\n    )[$__interval]\n  )\n)"
    }
   ]
  },
  {
   "title": "검색 로그 : [ $searchable_pattern ]",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n    (\n      {namespace=~\"$namespace\", namespace!~\"monitoring\", container=~\"$container_name\", pod=~\"$pod_name\"}\n        |~ \"(?i)$searchable_pattern\"\n        != \"caller=metrics.go\"\n        != \"var-searchable_pattern\"\n        !~ \"(?i)no_error\"\n    )[$__interval]\n  )\n)"
    }
   ]
  },
  {
   "title": "실시간 로그",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", namespace!~\"monitoring\", container=~\"$container_name\", pod=~\"$pod_name\"}\n  |~ \"(?i)$searchable_pattern\"\n  != \"caller=metrics.go\" \n  != \"var-searchable_pattern\"\n  !~ \"(?i)no_error\"\n  | pattern `<ts> <stream> <_> <msg>` \n  | line_format \"📢{{.namespace}}/{{.pod}}\\t📝{{.msg}}\""
    }
   ]
  },
  {
   "title": "검색어: [ $searchable_pattern ] - 도넛 차트",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n    (\n      {namespace=~\"$namespace\", namespace!~\"monitoring\", container=~\"$container_name\", pod=~\"$pod_name\"}\n        |~ \"(?i)$searchable_pattern\"\n        != \"caller=metrics.go\"\n        !~ \"(?i)no_error\"\n        != \"var-searchable_pattern\"\n\n    )[$__range]\n  )\n)\nby (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "검색어: [ $searchable_pattern ] - Rate per Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    (\n      {namespace=~\"$namespace\", namespace!~\"monitoring\", container=~\"$container_name\", pod=~\"$pod_name\"}\n        |~ \"(?i)$searchable_pattern\"\n        != \"caller=metrics.go\"\n        != \"var-searchable_pattern\"\n        !~ \"(?i)no_error\"\n    )[30s]\n  )\n)\nby (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "검색어: [ $searchable_pattern ] - (검색 로그 / 전체 로그)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n    ({namespace=~\"$namespace\", namespace!~\"monitoring\", container=~\"$container_name\", pod=~\"$pod_name\"}\n      |~ \"(?i)$searchable_pattern\"\n      != \"caller=metrics.go\"\n      != \"var-searchable_pattern\"\n      !~ \"(?i)no_error\")[$__interval]\n    )\n  ) * 100\n/\nsum(\n  count_over_time(\n    ({namespace=~\"$namespace\", namespace!~\"monitoring\", container=~\"$container_name\", pod=~\"$pod_name\"}\n      != \"caller=metrics.go\"\n      != \"var-searchable_pattern\"\n      !~ \"(?i)no_error\")[$__interval]\n  )\n)"
    }
   ]
  }
 ]
}